name: Bug Report
description: Report an Issue or Bug with the Package
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Sorry to hear you have a problem. Please provide as much details as possible so that we can solve this together.
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: What did you expect to happen?
          placeholder: I cannot currently do X thing because when I do, it breaks Y thing.
      validations:
          required: true
    - type: textarea
      id: how-to-reproduce
      attributes:
          label: How to reproduce the bug
          description: How did this occur? Please add any config values used and provide a set of reliable steps if possible.
          placeholder: When I do X I see Y.
      validations:
          required: true
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: What version of our Package are you running? Please be as specific as possible
          placeholder: 2.0.0
      validations:
          required: true
    - type: input
      id: php-version
      attributes:
          label: PHP Version
          description: What version of PHP are you running? Please be as specific as possible
          placeholder: 8.4.0
      validations:
          required: true
    - type: input
      id: laravel-version
      attributes:
        label: Laravel Version
        description: What version of Laravel are you running? Please be as specific as possible
        placeholder: 12.0.0
      validations:
        required: true
    - type: textarea
      id: notes
      attributes:
          label: Notes
          description: Use this field to provide any other notes that you feel might be relevant to the issue.
      validations:
          required: false
