blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/bilfeldt/laravel-http-client-logger/discussions/new?category=q-a
    about: Ask the community for help
  - name: Suggest a feature
    url: https://github.com/bilfeldt/laravel-http-client-logger/discussions/new?category=ideas
    about: Share ideas for new features
